### ISSUE TITLE
user docker2exe for temporary windows executables?

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#101]
https://github.com/rzane/docker2exe

**Comment by TokyoghoulEs** [comment]
How can I install using Docker on different systems?

**Comment by TokyoghoulEs** [comment]
How can I install using Docker on different systems?

**Comment by caryoscelus** [comment]
install docker (or its alternative) using whatever method is recommended on your system and then build docker image and run a container ([more details here](https://github.com/zeronet-conservancy/zeronet-conservancy?tab=readme-ov-file#alternatively-build-docker-image)). unfortunately i didn't have the time to deal with docker lately, so there's no pre-built images yet

**Comment by Tanvir1337x** [comment]
dockerfile needs to be updated. I'm getting error when I run using docker.

**Comment by caryoscelus** [comment]
@Tanvir1337x what kind of errors? can you post a log?

**Comment by Tanvir1337x** [comment]
> @Tanvir1337x what kind of errors? can you post a log?

```
zeronet-conservancy on  main via 🐍 
:: docker build -t 0net-conservancy:latest . -f docker/Dockerfile
[+] Building 3.2s (12/12) FINISHED                                                                                                                                       docker:default
 => [internal] load build definition from Dockerfile                                                                                                                               0.0s
 => => transferring dockerfile: 644B                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/python:3.12-alpine                                                                                                              2.1s
 => [internal] load .dockerignore                                                                                                                                                  0.0s
 => => transferring context: 73B                                                                                                                                                   0.0s
 => [1/7] FROM docker.io/library/python:3.12-alpine@sha256:bb94273467caf397de28b4e6dd09ca4a2dd1b53fa9b130d5b2c7c82719258356                                                        0.0s
 => [internal] load build context                                                                                                                                                  0.1s
 => => transferring context: 22.69MB                                                                                                                                               0.1s
 => CACHED [2/7] RUN apk --update --no-cache --no-progress add git gcc libffi-dev musl-dev make openssl g++ autoconf automake libtool                                              0.0s
 => CACHED [3/7] RUN adduser -u 1600 -D service-0net                                                                                                                               0.0s
 => CACHED [4/7] WORKDIR /home/service-0net                                                                                                                                        0.0s
 => CACHED [5/7] COPY requirements.txt .                                                                                                                                           0.0s
 => CACHED [6/7] RUN python3 -m pip install -r requirements.txt                                                                                                                    0.0s
 => [7/7] COPY . .                                                                                                                                                                 0.2s
 => exporting to image                                                                                                                                                             0.5s
 => => exporting layers                                                                                                                                                            0.5s
 => => writing image sha256:23c3b8f205bc641e1c5b11f20baf28bb9665cf93843f8081e5563c52ede1305c                                                                                       0.0s
 => => naming to docker.io/library/0net-conservancy:latest                                                                                                                         0.0s

 2 warnings found (use docker --debug to expand):
 - JSONArgsRecommended: JSON arguments recommended for ENTRYPOINT to prevent unintended behavior related to OS signals (line 19)
 - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 23)
 -
```

```bash
zeronet-conservancy on  main via 🐍 
:: docker run --rm -it -v /home/user/docker/0net-conservancy:/app/data -p 43111:43110 -p 26553:26552 0net-conservancy:latest
/home/service-0net
Traceback (most recent call last):
  File "/home/service-0net/src/Config.py", line 27, in __init__
    from . import Build
ImportError: cannot import name 'Build' from 'src' (/home/service-0net/src/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/service-0net/zeronet.py", line 4, in <module>
    from src.Config import config
  File "/home/service-0net/src/Config.py", line 856, in <module>
    config = Config(sys.argv)
             ^^^^^^^^^^^^^^^^
  File "/home/service-0net/src/Config.py", line 32, in __init__
    self.commit = Git.commit() or 'unknown'
                  ^^^^^^^^^^^^
  File "/home/service-0net/src/util/Git.py", line 53, in commit
    dirty = '-dirty' if _repo.is_dirty() else ''
                        ^^^^^^^^^^^^^^^^
  File "/home/service-0net/.local/lib/python3.12/site-packages/git/repo/base.py", line 949, in is_dirty
    if osp.isfile(self.index.path) and len(self.git.diff("--cached", *default_args)):
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/service-0net/.local/lib/python3.12/site-packages/git/cmd.py", line 986, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/service-0net/.local/lib/python3.12/site-packages/git/cmd.py", line 1598, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/service-0net/.local/lib/python3.12/site-packages/git/cmd.py", line 1388, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git diff --cached --abbrev=40 --full-index --raw
  stderr: 'error: unknown option `cached'
usage: git diff --no-index [<options>] <path> <path>

Diff output format options
    -p, --patch           generate patch
    -s, --no-patch        suppress diff output
    -u                    generate patch
    -U, --unified[=<n>]   generate diffs with <n> lines context
    -W, --[no-]function-context
                          generate diffs with <n> lines context
    --raw                 generate the diff in raw format
    --patch-with-raw      synonym for '-p --raw'
    --patch-with-stat     synonym for '-p --stat'
    --numstat             machine friendly --stat
    --shortstat           output only the last line of --stat
    -X, --dirstat[=<param1>,<param2>...]
                          output the distribution of relative amount of changes for each sub-directory
    --cumulative          synonym for --dirstat=cumulative
    --dirstat-by-file[=<param1>,<param2>...]
                          synonym for --dirstat=files,<param1>,<param2>...
    --check               warn if changes introduce conflict markers or whitespace errors
    --summary             condensed summary such as creations, renames and mode changes
    --name-only           show only names of changed files
    --name-status         show only names and status of changed files
    --stat[=<width>[,<name-width>[,<count>]]]
                          generate diffstat
    --stat-width <width>  generate diffstat with a given width
    --stat-name-width <width>
                          generate diffstat with a given name width
    --stat-graph-width <width>
                          generate diffstat with a given graph width
    --stat-count <count>  generate diffstat with limited lines
    --[no-]compact-summary
                          generate compact summary in diffstat
    --binary              output a binary diff that can be applied
    --[no-]full-index     show full pre- and post-image object names on the "index" lines
    --[no-]color[=<when>] show colored diff
    --ws-error-highlight <kind>
                          highlight whitespace errors in the 'context', 'old' or 'new' lines in the diff
    -z                    do not munge pathnames and use NULs as output field terminators in --raw or --numstat
    --[no-]abbrev[=<n>]   use <n> digits to display object names
    --src-prefix <prefix> show the given source prefix instead of "a/"
    --dst-prefix <prefix> show the given destination prefix instead of "b/"
    --line-prefix <prefix>
                          prepend an additional prefix to every line of output
    --no-prefix           do not show any source or destination prefix
    --default-prefix      use default prefixes a/ and b/
    --inter-hunk-context <n>
                          show context between diff hunks up to the specified number of lines
    --output-indicator-new <char>
                          specify the character to indicate a new line instead of '+'
    --output-indicator-old <char>
                          specify the character to indicate an old line instead of '-'
    --output-indicator-context <char>
                          specify the character to indicate a context instead of ' '

Diff rename options
    -B, --break-rewrites[=<n>[/<m>]]
                          break complete rewrite changes into pairs of delete and create
    -M, --find-renames[=<n>]
                          detect renames
    -D, --irreversible-delete
                          omit the preimage for deletes
    -C, --find-copies[=<n>]
                          detect copies
    --[no-]find-copies-harder
                          use unmodified files as source to find copies
    --no-renames          disable rename detection
    --[no-]rename-empty   use empty blobs as rename source
    --[no-]follow         continue listing the history of a file beyond renames
    -l <n>                prevent rename/copy detection if the number of rename/copy targets exceeds given limit

Diff algorithm options
    --minimal             produce the smallest possible diff
    -w, --ignore-all-space
                          ignore whitespace when comparing lines
    -b, --ignore-space-change
                          ignore changes in amount of whitespace
    --ignore-space-at-eol ignore changes in whitespace at EOL
    --ignore-cr-at-eol    ignore carrier-return at the end of line
    --ignore-blank-lines  ignore changes whose lines are all blank
    -I, --[no-]ignore-matching-lines <regex>
                          ignore changes whose all lines match <regex>
    --[no-]indent-heuristic
                          heuristic to shift diff hunk boundaries for easy reading
    --patience            generate diff using the "patience diff" algorithm
    --histogram           generate diff using the "histogram diff" algorithm
    --diff-algorithm <algorithm>
                          choose a diff algorithm
    --anchored <text>     generate diff using the "anchored diff" algorithm
    --word-diff[=<mode>]  show word diff, using <mode> to delimit changed words
    --word-diff-regex <regex>
                          use <regex> to decide what a word is
    --color-words[=<regex>]
                          equivalent to --word-diff=color --word-diff-regex=<regex>
    --[no-]color-moved[=<mode>]
                          moved lines of code are colored differently
    --[no-]color-moved-ws <mode>
                          how white spaces are ignored in --color-moved

Other diff options
    --[no-]relative[=<prefix>]
                          when run from subdir, exclude changes outside and show relative paths
    -a, --[no-]text       treat all files as text
    -R                    swap two inputs, reverse the diff
    --[no-]exit-code      exit with 1 if there were differences, 0 otherwise
    --[no-]quiet          disable all output of the program
    --[no-]ext-diff       allow an external diff helper to be executed
    --[no-]textconv       run external text conversion filters when comparing binary files
    --ignore-submodules[=<when>]
                          ignore changes to submodules in the diff generation
    --submodule[=<format>]
                          specify how differences in submodules are shown
    --ita-invisible-in-index
                          hide 'git add -N' entries from the index
    --ita-visible-in-index
                          treat 'git add -N' entries as real in the index
    -S <string>           look for differences that change the number of occurrences of the specified string
    -G <regex>            look for differences that change the number of occurrences of the specified regex
    --pickaxe-all         show all changes in the changeset with -S or -G
    --pickaxe-regex       treat <string> in -S as extended POSIX regular expression
    -O <file>             control the order in which files appear in the output
    --rotate-to <path>    show the change in the specified path first
    --skip-to <path>      skip the output to the specified path
    --find-object <object-id>
                          look for differences that change the number of occurrences of the specified object
    --diff-filter [(A|C|D|M|R|T|U|X|B)...[*]]
                          select files by diff type
    --output <file>       output to a specific file
'
```

**Comment by Tanvir1337x** [comment]
Next updates coming when?
