### ISSUE TITLE
Can't install dependencies on 22/Jammy (ARM)

### ISSUE THREAD

**Issue by d47081** [zeronet-conservancy/zeronet-conservancy#129]
`./start-venv.sh`

```
Ignoring gevent: markers 'python_version <= "3.6"' don't match your environment
Ignoring greenlet: markers 'python_version <= "3.6"' don't match your environment
```

Must I downgrade python 3.10 or wait for the ZNC upgrade? Just not pretty familiar with python to fix that.
Issue could be actual for the report here.

**Comment by caryoscelus** [comment]
these should be fine . that part of `requirements.txt` is kept for compatibility with older python versions (which required additional dependencies) , not to prevent from running newer ones . possibly there's a way to shut `pip` about those "warnings" , that needs to be investigated further

does the script work otherwise ?

**Comment by d47081** [comment]
Thanks for reply. The problem with running with following errors:

`./start-venv.sh`

```
Ignoring gevent: markers 'python_version <= "3.6"' don't match your environment
Ignoring greenlet: markers 'python_version <= "3.6"' don't match your environment
Collecting gevent>=20.9.0
  Using cached gevent-21.12.0.tar.gz (6.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      Collecting setuptools>=40.8.0
        Using cached setuptools-63.2.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting Cython>=3.0a9
        Using cached Cython-3.0.0a10-py2.py3-none-any.whl (1.1 MB)
      Collecting cffi>=1.12.3
        Using cached cffi-1.15.1.tar.gz (508 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting greenlet<2.0,>=0.4.17
        Using cached greenlet-1.1.2.tar.gz (91 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pycparser
        Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
      Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
      Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
      Installing collected packages: wheel, setuptools, pycparser, greenlet, Cython, cffi
        Running setup.py install for greenlet: started
        Running setup.py install for greenlet: finished with status 'done'
        Running setup.py install for cffi: started
        Running setup.py install for cffi: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for cffi did not run successfully.
        │ exit code: 1
        ╰─> [38 lines of output]
            running install
            /home/zeronet-conservancy/venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
              warnings.warn(
            running build
            running build_py
            creating build
            creating build/lib.linux-armv7l-3.10
            creating build/lib.linux-armv7l-3.10/cffi
            copying cffi/verifier.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/recompiler.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/pkgconfig.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/model.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/lock.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/error.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/cparser.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/commontypes.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/api.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/__init__.py -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/_embedding.h -> build/lib.linux-armv7l-3.10/cffi
            copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.10/cffi
            running build_ext
            building '_cffi_backend' extension
            creating build/temp.linux-armv7l-3.10
            creating build/temp.linux-armv7l-3.10/c
            arm-linux-gnueabihf-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/home/zeronet-conservancy/venv/include -I/usr/include/python3.10 -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.10/c/_cffi_backend.o
            c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
               15 | #include <ffi.h>
                  |          ^~~~~~~
            compilation terminated.
            error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> cffi
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/home/zeronet-conservancy/zeronet.py", line 173, in <module>
    start()
  File "/home/zeronet-conservancy/zeronet.py", line 169, in start
    main()
  File "/home/zeronet-conservancy/zeronet.py", line 48, in main
    fancy_greet()
  File "/home/zeronet-conservancy/zeronet.py", line 24, in fancy_greet
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
```

**Comment by d47081** [comment]
fixed by installing `libffi-dev` dependency

`sudo apt install libffi-dev`

https://github.com/zeronet-conservancy/zeronet-conservancy/pull/130
