### ISSUE TITLE
Unhandled exception: [Errno 13] Permission denied: './data'

### ISSUE THREAD

**Issue by defder-su** [zeronet-conservancy/zeronet-conservancy#148]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.6
  * Operating system: macOS 10.13
  * Web browser: n/a
  * Tor status: always
  * Opened port: yes/no
  * Special configuration: none

#### Steps to reproduce:

  1. Install Nix package manager
  2. Install zeronet-conservancy by running `nix-env -iA nixpkgs.zeronet-conservancy`
  3. Run `zeronet`

#### Observed Results:

```
|||  __.  _. . _  .   . _    _.  _|_          _.   .   . _  .--   _. . _  .  .  
__.  . _    _.  .  .
|||   /  /_| |/  / \  |/ |  /_|   |     ==   /    / \  |/ |  \   /_| |/   |  |  
__|  |/ |  /     \_|
|||  /_. \_  |   \_/  |  |  \_    |.         \__  \_/  |  | ._|  \_  |     \/  
|__|  |  |  \__     |
|||                                                                             
_/
|||  v0.7.6

ERROR:root:Unhandled exception: [Errno 13] Permission denied: './data'
Traceback (most recent call last):
  File "/nix/store/mbnanbmwpv1n1a7wqh0xfzxfa5fikdw7-zeronet-conservancy-0.7.6/share/zeronet.py", line 52, in main
    import main
  File "/nix/store/mbnanbmwpv1n1a7wqh0xfzxfa5fikdw7-zeronet-conservancy-0.7.6/share/src/main.py", line 35, in <module>
    os.mkdir(config.data_dir)
PermissionError: [Errno 13] Permission denied: './data'
Traceback (most recent call last):
  File "/nix/store/mbnanbmwpv1n1a7wqh0xfzxfa5fikdw7-zeronet-conservancy-0.7.6/share/zeronet.py", line 52, in main
    import main
  File "/nix/store/mbnanbmwpv1n1a7wqh0xfzxfa5fikdw7-zeronet-conservancy-0.7.6/share/src/main.py", line 35, in <module>
    os.mkdir(config.data_dir)
PermissionError: [Errno 13] Permission denied: './data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/mbnanbmwpv1n1a7wqh0xfzxfa5fikdw7-zeronet-conservancy-0.7.6/share/zeronet.py", line 173, in <module>
    start()
  File "/nix/store/mbnanbmwpv1n1a7wqh0xfzxfa5fikdw7-zeronet-conservancy-0.7.6/share/zeronet.py", line 169, in start
    main()
  File "/nix/store/mbnanbmwpv1n1a7wqh0xfzxfa5fikdw7-zeronet-conservancy-0.7.6/share/zeronet.py", line 63, in main
    traceback.print_exc(file=open(error_log_path, "w"))
FileNotFoundError: [Errno 2] No such file or directory: './log/error.log'
```

#### Expected Results:

  * Start ZeroNet node successfully, using `~/Library/Application Support/ZeroNet` or some other folder for data.

**Comment by caryoscelus** [comment]
i've encountered this issue on NixOS , haven't had time to investigate it yet , but i'll get back to it ASAP

workaround should be passing `--start_dir <desired path>` , though i haven't tried that yet

**Comment by defder-su** [comment]
It works with the workaround.

However, I can't use Sidebar:
`Internal error: KeyError('donate_key'): 'donate_key'
UiWebsocket.py line 80 > 236 > SidebarPlugin.py line 558 > 462 > Translate.py line 90 > 79 > line 165 > 205 > 270 > 227 > Translate.py line 17`

**Comment by caryoscelus** [comment]
@defder-su are you using non-default localization ? sounds like a translation system bug

**Comment by defder-su** [comment]
Yes, I use Russian translation.

**Comment by fgaz** [comment]
This is because by default zeronet tries to use a `data` directory in the same directory as the executable (`./data`), but that will always fail for a packaged (=> read-only) zeronet. On NixOS we try to stay as close as upstream as possible, so I (the packager) didn't patch that behaviour. When using the NixOS module though, we take care of setting a valid data_dir: https://github.com/NixOS/nixpkgs/blob/45c9736ed69800a6ff2164fb4538c9e40dad25d6/nixos/modules/services/networking/zeronet.nix#L6

You're not using NixOS so the module doesn't apply and you'll have to pass data_dir manually (or through a configuration file).
Maybe this could be solved by defaulting data_dir to something like `$XDG_DATA_HOME/zeronet-conservancy/data`. The downside is that the previous behaviour of keeping everything in a directory is lost

**Comment by defder-su** [comment]
I used ZeroNetX, and have my data in $HOME/Library/Application Support/ZeroNet.
It's a problem with ZeroNet data folder location, generally. It would be good to have some environment variable like ZERONET_PATH. Then third party software could use zites as data sources. And node implementations too.

**Comment by caryoscelus** [comment]
@defder-su i've created a separate issue about translation (#149)

@fgaz there are several predefined data location changes based on where 0net locates itself , so it's only reasonable to write NixOS-specific detection or generalize existing "readonly" detection to actually detect read-only instead of path-guessing at

https://github.com/zeronet-conservancy/zeronet-conservancy/blob/master/src/Config.py#L74

> It would be good to have some environment variable like ZERONET_PATH

sounds reasonable , also wouldn't break existing behaviour in any way

**Comment by defder-su** [comment]
`which zeronet` returns `$HOME/.nix-profile/bin/zeronet`, by the way.
