### ISSUE TITLE
siteCreate is broken on Linux

### ISSUE THREAD

**Issue by woo3** [zeronet-conservancy/zeronet-conservancy#203]
### Step 1: Please describe your environment

  * ZeroNet version: v0.7.8.1
  * Operating system: Arch Linux
  * Web browser: Chrome
  * Tor status: always
  * Opened port: no
  * Special configuration: n/a

### Step 2: Describe the problem:

 ~/Dow/zeronet-conservancy-0.7.8.1  python zeronet.py siteCreate                  

|||   . . _  _._|_     _. . . _ .__ _.. _.  . __.. _  __.  .
|||  //\|/ |/_| |  == /  / \|/ |(  /_||/ |  | __||/ |/   \_|
|||  \_/|  |\_  |.    \__\_/|  |_) \_ |   \/ |__||  |\__ _/
|||
|||  v0.7.8.1

- Libsecp256k1 load failed: No module named 'coincurve'
- Version: 0.7.8.1 r5040, Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0], Gevent: 22.10.2
- Generating new privatekey (use_master_seed: True)...
- Generated using master seed from users.json, site index: 34607916
- ----------------------------------------------------------------------
- Site private key: 5Hqf96fpv87fdiHUBKbRFVq6pWdzYrWff2bWk5Y5v7u5ZdW6YWQ
-                   !!! ^ Save it now, required to modify the site ^ !!!
- Site address:     15upwTegecejq3HzJYC6QKjoemZT9dQixe
- ----------------------------------------------------------------------
- Creating directory structure...
- Unhandled exception: cannot import name 'Site' from partially initialized module 'Site.Site' (most likely due to a circular import) (/home/pc/Downloads/zeronet-conservancy-0.7.8.1/src/Site/Site.py)
Traceback (most recent call last):
  File "/home/pc/Downloads/zeronet-conservancy-0.7.8.1/zeronet.py", line 53, in main
    main.start()
  File "/home/pc/Downloads/zeronet-conservancy-0.7.8.1/src/main.py", line 612, in start
    actions.call(config.action, action_kwargs)
  File "/home/pc/Downloads/zeronet-conservancy-0.7.8.1/src/main.py", line 143, in call
    back = func(**kwargs)
  File "/home/pc/Downloads/zeronet-conservancy-0.7.8.1/src/main.py", line 198, in siteCreate
    from Site.Site import Site
  File "/home/pc/Downloads/zeronet-conservancy-0.7.8.1/src/Site/Site.py", line 27, in <module>
    from File import FileServer
  File "/home/pc/Downloads/zeronet-conservancy-0.7.8.1/src/File/__init__.py", line 1, in <module>
    from .FileServer import FileServer
  File "/home/pc/Downloads/zeronet-conservancy-0.7.8.1/src/File/FileServer.py", line 16, in <module>
    from Site import SiteManager
  File "/home/pc/Downloads/zeronet-conservancy-0.7.8.1/src/Site/SiteManager.py", line 17, in <module>
    from .Site import Site
ImportError: cannot import name 'Site' from partially initialized module 'Site.Site' (most likely due to a circular import) (/home/pc/Downloads/zeronet-conservancy-0.7.8.1/src/Site/Site.py)
---
Please report it: https://github.com/zeronet-conservancy/zeronet-conservancy/issues/new?template=bug-report.md

The supossedly created site absolutely does not show up in the zeronet/data folder.

#### Expected Results:

I want to be able to create a new ZN site with index.html, content.json, js folder as should be

**Comment by woo3** [comment]
@redarmyfaction Just out of curiosity, how does this differ from conservancy?

**Comment by woo3** [comment]
@redarmyfaction Yeah, I started getting that vibe a while back. I spoke to caryoscelus in the past, and they instantly came off as a mentally unstable weirdo. Thanks for recommending me this, do you have any platform I can message you on, like Telegram or Matrix

**Comment by woo3** [comment]
@redarmyfaction email me at woowuuwew@protonmail.com and I'll share there. Don't want "riza" con-artists intercepting us

**Comment by caryoscelus** [comment]
@woo3

> Just out of curiosity, how does this differ from conservancy?

enhanced is created by @wandrien who have abandoned the project before new security vulnerability was discovered so it doesn't have a fix and isn't being developed anymore. otherwise it has somewhat major rewrite of some parts (which could be beneficial, but some users reported issues). some minor improvements have been integrated into conservancy

anyway thanks for reporting the bug. be careful with trolls and good luck

**Comment by caryoscelus** [comment]
@woo3 you can try reverting 427bea581bc5cb7821930e0f81fbcbeb61a12b84 and see if it works

in general i'm skeptical towards keeping these old commands as well as the whole mess that `zeronet.py` is around, so not sure fixing this would be a priority

**Comment by imachug** [comment]
> @caryoscelus is lying, there isn't any "security vulnerability".

There is a vulnerability, I found it myself

**Comment by woo3** [comment]
These pings, damn. 
I admit that my frustration at the errors rubbed off on my post in this thread. 
For the record ZN Conservancy definitely has the potential to be something great, but the devs need to devote serious time and money into. @imachug Please contact me at woowuuwew@protonmail.com

**Comment by woo3** [comment]
@redarmyfaction You are a hungry latin american who has zero funding/financing for his own projects

Which explains why you FUD other ZN projects to sway others to yours.

**Comment by caryoscelus** [comment]
could you please avoid personal and offtopic discussion here ? it clutters discussion of still open issue
