### ISSUE TITLE
Cant start zeronet

### ISSUE THREAD

**Issue by Dimoon12** [zeronet-conservancy/zeronet-conservancy#206]
### Step 1: Please describe your environment
  * Python version:  python 3.10.9
  * ZeroNet version: v0.7.8.1
  * Operating system:  Manjaro linux
  * Web browser: _____
  * Tor status: ___
  * Opened port: yes
  * Special configuration: No

### Step 2: Describe the problem:
systemctl start zeronet cant start service

#### Steps to reproduce:

  1. Install zeronet through AUR, package: zeronet-conservancy
  2. Make attempt to start it

#### Observed Results:
```
Systemdlog:

фев 25 19:30:22 Macmeow systemd[1]: Started ZeroNet: a decentralized web platform.
фев 25 19:30:22 Macmeow zeronet[3839]: |||   . . _  _._|_     _. . . _ .__ _.. _.  . __.. _  __.  .
фев 25 19:30:22 Macmeow zeronet[3839]: |||  //\|/ |/_| |  == /  / \|/ |(  /_||/ |  | __||/ |/   \_|
фев 25 19:30:22 Macmeow zeronet[3839]: |||  \_/|  |\_  |.    \__\_/|  |_) \_ |   \/ |__||  |\__ _/
фев 25 19:30:22 Macmeow zeronet[3839]: |||
фев 25 19:30:22 Macmeow zeronet[3839]: |||  v0.7.8.1
фев 25 19:30:23 Macmeow zeronet[3839]: ERROR:root:Unhandled exception: Entry points must be listed in groups
фев 25 19:30:23 Macmeow zeronet[3839]: Traceback (most recent call last):
фев 25 19:30:23 Macmeow zeronet[3839]:   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2868, in get_entry_map
фев 25 19:30:23 Macmeow zeronet[3839]:     ep_map = self._ep_map
фев 25 19:30:23 Macmeow zeronet[3839]:   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2834, in __getattr__
фев 25 19:30:23 Macmeow zeronet[3839]:     raise AttributeError(attr)
фев 25 19:30:23 Macmeow zeronet[3839]: AttributeError: _ep_map
фев 25 19:30:23 Macmeow zeronet[3839]: During handling of the above exception, another exception occurred:
фев 25 19:30:23 Macmeow zeronet[3839]: Traceback (most recent call last):
фев 25 19:30:23 Macmeow zeronet[3839]:   File "/opt/zeronet/zeronet.py", line 52, in main
фев 25 19:30:23 Macmeow zeronet[3839]:     import main
фев 25 19:30:23 Macmeow zeronet[3839]:   File "/opt/zeronet/src/main.py", line 22, in <module>
фев 25 19:30:23 Macmeow zeronet[3839]:     gevent.monkey.patch_all(thread=False, subprocess=False)
фев 25 19:30:23 Macmeow zeronet[3839]:   File "/usr/lib/python3.10/site-packages/gevent/monkey.py", line 1255, in patch_all
фев 25 19:30:23 Macmeow zeronet[3839]:     _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
фев 25 19:30:23 Macmeow zeronet[3839]:   File "/usr/lib/python3.10/site-packages/gevent/monkey.py", line 190, in _notify_patch
фев 25 19:30:23 Macmeow zeronet[3839]:     notify_and_call_entry_points(event)
фев 25 19:30:23 Macmeow zeronet[3839]:   File "/usr/lib/python3.10/site-packages/gevent/events.py", line 103, in notify_and_call_entry_points
фев 25 19:30:23 Macmeow zeronet[3839]:     for plugin in iter_entry_points(event.ENTRY_POINT_NAME):
фев 25 19:30:23 Macmeow zeronet[3839]:   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 698, in <genexpr>
фев 25 19:30:23 Macmeow zeronet[3839]:     for entry in dist.get_entry_map(group).values()
фев 25 19:30:23 Macmeow zeronet[3839]:   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2870, in get_entry_map
фев 25 19:30:23 Macmeow zeronet[3839]:     ep_map = self._ep_map = EntryPoint.parse_map(
фев 25 19:30:23 Macmeow zeronet[3839]:   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2564, in parse_map
фев 25 19:30:23 Macmeow zeronet[3839]:     raise ValueError("Entry points must be listed in groups")
фев 25 19:30:23 Macmeow zeronet[3839]: ValueError: Entry points must be listed in groups
фев 25 19:30:23 Macmeow zeronet[3839]: ---

```

#### Expected Results:

  * Normal start of zeronet

**Comment by caryoscelus** [comment]
thanks for reporting. i've been away for a while, but i'll try to get to this issue asap

meanwhile, can you check if the same happens if you use `zeronet-conservancy` from source code via `venv`?

**Comment by caryoscelus** [comment]
@Dimoon12 did you have this on a fresh setup ? while i can't reproduce this , i've just tried launching `zeronet-conservancy` on manjaro and it also had a weird glitch : it didn't work until i reinstalled python-base58 dependency (`base58` was not available as python module from anywhere , in fact) . so my hypothesis would be that something could be broken in dependencies

in particular judging from the output you posted , something can be wrong with `pkg_resources` , which i believe is part of `python-setuptools` so you can try reinstalling that
