### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#250]
this happens randomly on startup and doesn't seem to affect anything later , but investigation is warranted

similar (same?) issue reported [here](https://github.com/HelloZeroNet/ZeroNet/issues/2838)

```
Unhandled exception: RuntimeError: dictionary changed size during iteration in <gevent>/greenlet.py line 908 > SiteManager.py line 202 > ContentFilterPlugin.py line 43 > SiteManager.py line 188 > Site.py line 131 > MergerSitePlugin.py line 399 > 351
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "src/Site/SiteManager.py", line 202, in need
    site = self.add(address, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/ContentFilter/ContentFilterPlugin.py", line 43, in add
    return super(SiteManagerPlugin, self).add(address, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/Site/SiteManager.py", line 188, in add
    site.saveSettings()
  File "src/Site/Site.py", line 131, in saveSettings
    SiteManager.site_manager.saveDelayed()
  File "plugins/MergerSite/MergerSitePlugin.py", line 399, in saveDelayed
    self.updateMergerSites()
  File "plugins/MergerSite/MergerSitePlugin.py", line 351, in updateMergerSites
    for site in self.sites.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by caryoscelus** [comment]
seems to correlate with lacking files on sites
