### ISSUE TITLE
Annoying Migration functionality that doesn't work at all.

### ISSUE THREAD

**Issue by Zevobla** [zeronet-conservancy/zeronet-conservancy#279]
### Step 1: Please describe your environment

  * ZeroNet version: 
  * Operating system: macOS 15.0.1 (darwin-arm64)

#### Steps to reproduce:

  1. Install original ZeroNet on macOS
  2. Ensure that in the ZeroNet directory "/Users/`whoami`/Library/Application Support/ZeroNet" there is zeronet.conf and data folder
  3. Just start zeronet-conservancy's start-venv.sh

#### Observed Results:

```You have old data in `.`. Migrate to new format to `/Users/user_name/Library/Application Support/zeronet-conservancy`? [Y/n]n
Traceback (most recent call last):
  File "/Users/user_name/Documents/zeronet-conservancy/zeronet.py", line 6, in <module>
    from src.Config import config
  File "/Users/user_name/Documents/zeronet-conservancy/src/Config.py", line 856, in <module>
    config = Config(sys.argv)
             ^^^^^^^^^^^^^^^^
  File "/Users/user_name/Documents/zeronet-conservancy/src/Config.py", line 64, in __init__
    self.configurePaths(argv)
  File "/Users/user_name/Documents/zeronet-conservancy/src/Config.py", line 126, in configurePaths
    raise ex
  File "/Users/user_name/Documents/zeronet-conservancy/src/Config.py", line 124, in configurePaths
    self.start_dir = self.maybeMigrate(old_dir, new_dir, no_migrate, silent_migrate)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_name/Documents/zeronet-conservancy/src/Config.py", line 190, in maybeMigrate
    return self.askMigrate(old_dir, new_dir, silent_migrate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_name/Documents/zeronet-conservancy/src/Config.py", line 160, in askMigrate
    raise StartupError('Migration refused')
src.Config.StartupError: Migration refused```

#### Expected Results:

Nothing to do with original configuration.

PS: I will try to fix it

**Comment by caryoscelus** [comment]
hi there! yeah, i shouldn't have switched the main branch to include new dir structure before migration is implemented. right now you can use the older `master` branch, or, since you don't want to mix with old installation you can use `--no-migration` flag

>  I will try to fix it

that'd be awesome!

**Comment by Zevobla** [comment]
And @caryoscelus can u please check my PR #281 ?

**Comment by caryoscelus** [comment]
sorry, it should be `--no-migrate` rather

**Comment by slrslr** [comment]
> it should be `--no-migrate` rather

I have cloned from git today (git clone --recursive "https://github.com/zeronet-conservancy/zeronet-conservancy.git") and this continuously fails:

# ./zeronet.sh --version --no-migrate
```
/root/zeronet
You have old data in `.`. Migrate to new format to `/root/.local/share/zeronet-conservancy`? [Y/n]n
Traceback (most recent call last):
  File "/root/zeronet/zeronet.py", line 4, in <module>
    from src.Config import config
  File "/root/zeronet/src/Config.py", line 856, in <module>
    config = Config(sys.argv)
             ^^^^^^^^^^^^^^^^
  File "/root/zeronet/src/Config.py", line 64, in __init__
    self.configurePaths(argv)
  File "/root/zeronet/src/Config.py", line 126, in configurePaths
    raise ex
  File "/root/zeronet/src/Config.py", line 124, in configurePaths
    self.start_dir = self.maybeMigrate(old_dir, new_dir, no_migrate, silent_migrate)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/zeronet/src/Config.py", line 190, in maybeMigrate
    return self.askMigrate(old_dir, new_dir, silent_migrate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/zeronet/src/Config.py", line 160, in askMigrate
    raise StartupError('Migration refused')
src.Config.StartupError: Migration refused
```

**Comment by caryoscelus** [comment]
@d47081 yeah, it should've been or rather should've stayed in experimental branch. I overestimated the speed at which I would be able to implement changes..
