### ISSUE TITLE
can't launch zeronet.py

### ISSUE THREAD

**Issue by d4708** [zeronet-conservancy/zeronet-conservancy#68]
Suppose after some updates (maybe in requirements.txt), 0net instance crash on launch with error: 

`zeronet.py`

```
Unhandled exception: argument --ui_password: conflicting option string: --ui_password

Traceback (most recent call last):
  File "/zeronet-conservancy/zeronet.py", line 52, in main
    import main
  File "/zeronet-conservancy/src/main.py", line 76, in <module>
    config.loadPlugins()
  File "/zeronet-conservancy/src/Config.py", line 546, in loadPlugins
    ConfigPlugin(self)
  File "/zeronet-conservancy/src/Config.py", line 541, in __init__
    self.createArguments()
  File "/zeronet-conservancy/plugins/disabled-UiPassword/UiPasswordPlugin.py", line 164, in createArguments
    return super(ConfigPlugin, self).createArguments()
  File "/zeronet-conservancy/plugins/Zeroname/SiteManagerPlugin.py", line 69, in createArguments
    return super(ConfigPlugin, self).createArguments()
  File "/zeronet-conservancy/plugins/UiPassword/UiPasswordPlugin.py", line 162, in createArguments
    group.add_argument('--ui_password', help='Password to access UiServer', default=None, metavar="password")
  File "/usr/lib/python3.9/argparse.py", line 1446, in add_argument
    return self._add_action(action)
  File "/usr/lib/python3.9/argparse.py", line 1648, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python3.9/argparse.py", line 1460, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.9/argparse.py", line 1597, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.9/argparse.py", line 1606, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --ui_password: conflicting option string: --ui_password
```

plugins.json
```
{
  "builtin": {
    "UiPassword": {
      "enabled": true
    }
  }
}
```
zeronet.conf pasword the same

```
ui_password = ***
```

**Comment by caryoscelus** [comment]
what happens if you remove/comment out ui_password from .conf?

**Comment by d4708** [comment]
nothing, it was server crash also, so I can launch only with new data folder initiation.

maybe some database index are broken, won't to download all content collected again..

**Comment by d4708** [comment]
the keyword is:
```
File "/zeronet-conservancy/plugins/disabled-UiPassword/UiPasswordPlugin.py", line 164, in createArguments
    return super(ConfigPlugin, self).createArguments()
```

removed `UiPassword` folder and renamed original `disabled-UiPassword` to `UiPassword`

**Comment by caryoscelus** [comment]
so there's some problem with enabling plugins via config vs renaming directories . i think i've seen that before . gonna make a separate issue on that

**Comment by d47081** [comment]
for a note, to launch 0net with the UiPassword plugin, an option 
`python3 zeronet.py --ui_ip` must to be provided in `start-venv.sh` file
