### ISSUE TITLE
0.7.5 r5010 Unhandled exception: KeyError: 'cert_auth_type' in <gevent>/greenlet.py line 906 > Worker.py line 208 > 154 > BigfilePlugin.py line 404 > ContentManager.py line 1006 > 988 > 833

### ISSUE THREAD

**Issue by slrslr** [zeronet-conservancy/zeronet-conservancy#83]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.5 r5010
  * Operating system: Linux Debian 11
  * Tor status: available
  * Opened port: yes

### Step 2: Describe the problem:

Git cloned the master branch, installed requirements.txt modules, copied my zeronetx zeronet.conf and link data directory. Ran "python3 zeronet.py"

->
```
Unhandled exception: KeyError: 'cert_auth_type' in <gevent>/greenlet.py line 906 > Worker.py line 208 > 154 > BigfilePlugin.py line 404 > ContentManager.py line 1006 > 988 > 833
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "zeronetc/src/Worker/Worker.py", line 208, in downloader
    success = self.handleTask(task)
  File "zeronetc/src/Worker/Worker.py", line 154, in handleTask
    if task["site"].content_manager.verifyFile(task["inner_path"], buff) is None:
  File "zeronetc/plugins/Bigfile/BigfilePlugin.py", line 404, in verifyFile
    return super(ContentManagerPlugin, self).verifyFile(inner_path, file, ignore_same)
  File "zeronetc/src/Content/ContentManager.py", line 1006, in verifyFile
    raise err
  File "zeronetc/src/Content/ContentManager.py", line 988, in verifyFile
    if inner_path != "content.json" and not self.verifyCert(inner_path, new_content):  # Check if cert valid
  File "zeronetc/src/Content/ContentManager.py", line 833, in verifyCert
    return self.verifyCertSign(rules["user_address"], content["cert_auth_type"], name, cert_address, content["cert_sign"])
KeyError: 'cert_auth_type'

```

several minutes later:
`Ui.UiServer Error 500: UiWSGIHandler error: TypeError: object of type 'generator' has no len()`

Admin site is loading though, but lists default sites, not all sites that I have in data/{users.json,sites.json} directory (data/ is a symbolic link to different HDD (worked in zeronetx). Also the configuration was not loaded from zeronet.conf apparently. ZNC prompts ADMIN permission https://github.com/zeronet-conservancy/zeronet-conservancy/issues/82

**Comment by slrslr** [comment]
I can no longer see this error in logs..
