### ISSUE TITLE
make sure tor password authentication works

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#92]
this is useful for docker composition

**Comment by prtngn** [comment]
```
(venv) ➜  zeronet-conservancy git:(master) ✗ python3 zeronet.py --tor_password test

|||  __.  _. . _  .   . _    _.  _|_          _.   .   . _  .--   _. . _  .  .  __.  . _    _.  .  .
|||   /  /_| |/  / \  |/ |  /_|   |     ==   /    / \  |/ |  \   /_| |/   |  |  __|  |/ |  /     \_|
|||  /_. \_  |   \_/  |  |  \_    |.         \__  \_/  |  | ._|  \_  |     \/  |__|  |  |  \__     |
|||                                                                                              _/
|||  v0.7.5+

- Libsecpk256k1 loaded: Lib in 0.011s
- Unhandled exception: None
Traceback (most recent call last):
  File "/Users/prtngn/Programming/Sandboxes/zeronet-conservancy/zeronet.py", line 53, in main
    main.start()
  File "/Users/prtngn/Programming/Sandboxes/zeronet-conservancy/src/main.py", line 601, in start
    action_kwargs = config.getActionArguments()
  File "/Users/prtngn/Programming/Sandboxes/zeronet-conservancy/src/Config.py", line 380, in getActionArguments
    arguments = self.parser._subparsers._group_actions[0].choices[self.action]._actions[1:]  # First is --version
KeyError: None
---
Please report it: https://github.com/zeronet-conservancy/zeronet-conservancy/issues/new?template=bug-report.md
```

**Comment by caryoscelus** [comment]
looks like this is platform/library version dependent . works fine on my android

tor version 0.4.6.10

the launch commands are

```
tor --ControlPort 9051 --HashedControlPassword <password_hash>
```

and

```
python3 zeronet.py --tor_password <password>
```

**Comment by caryoscelus** [comment]
but then since it crashes before reaching tor , the most important is python version or argparse related stuff:

```
python 3.10.4
```

**Comment by caryoscelus** [comment]
as @prtngn found out and i confirmed , this is because of some special treatment of password `test`

otherwise password authentication seems to work just fine

**Comment by caryoscelus** [comment]
further info : this is due to subparser commands , using any of them as tor password triggers argparse considering them commands rather than belonging to `--tor-password` option

**Comment by caryoscelus** [comment]
if subparser command is placed at the end of arguments , everything works fine . so running `python zeronet.py --tor_password test main` works

that might be a valid workaround for container purposes

**Comment by caryoscelus** [comment]
closing this in favour of more generic #96 . nothing seems to be wrong with tor password auth per se
